// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "61558b5a-5582-4c88-acd0-6211e13b98f2");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1558975006);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1558975126);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1558978126);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1558974766);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1558974646);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1558974886);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1558975366);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1558975246);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1558974495);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"39348\":1558974501736,\"39363\":1558976991060,\"39376\":1558974501736,\"39389\":1558974501736}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{71b984a2-e4de-40de-a0ab-5ea080b39a47}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1558940400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1558978137342");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1558979947342");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1558978105443");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1558981705443");
user_pref("browser.search.region", "CA");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1558977748");
user_pref("browser.slowStartup.averageTime", 4058);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"webide-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1558974502213");
user_pref("devtools.debugger.prefs-schema-version", "1.0.5");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "1d9803fb1ce24671871a8d121845f8c0");
user_pref("extensions.blocklist.lastModified", "Mon, 27 May 2019 11:04:50 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1558975007);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190128144255");
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"6206fcbd-ca49-41c8-9673-c70eb081d2e7\",\"screenshots@mozilla.org\":\"f831b8d2-cce1-439d-ba33-99da15da300b\",\"webcompat-reporter@mozilla.org\":\"394ade83-fcc2-4d64-98ae-d9db496d827d\",\"webcompat@mozilla.org\":\"fa8d8b4d-3333-4019-9f57-b5d834668242\",\"baidu-code-update@mozillaonline.com\":\"2841650d-ef07-4ad2-aed3-b7a5167a8c76\",\"fxmonitor@mozilla.org\":\"b6eaf701-4b3d-4c6f-8331-32caa0f15522\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.benchmark.vp9.fps", 60);
user_pref("media.benchmark.vp9.versioncheck", 5);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1558974678);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1558974677);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "39f87bf3-0057-4d40-a847-dfc35ea003f8");
user_pref("security.sandbox.plugin.tempDirSuffix", "c511a8cf-5748-4149-aef3-1a7cca671586");
user_pref("services.blocklist.addons.checked", 1558974728);
user_pref("services.blocklist.gfx.checked", 1558974728);
user_pref("services.blocklist.onecrl.checked", 1558974728);
user_pref("services.blocklist.pinning.checked", 1558974728);
user_pref("services.blocklist.plugins.checked", 1558974728);
user_pref("services.settings.clock_skew_seconds", -43);
user_pref("services.settings.last_update_seconds", 1558975320);
user_pref("services.settings.main.language-dictionaries.last_check", 1558974728);
user_pref("services.settings.main.onboarding.last_check", 1558974728);
user_pref("services.settings.main.sites-classification.last_check", 1558974728);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1570016344);
user_pref("toolkit.telemetry.cachedClientID", "9014606a-5db9-44ba-aef6-b91b7c48f551");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
